CREATE TABLE USER (ID INTEGER AUTO_INCREMENT NOT NULL, PASSWORD VARCHAR(255), USERNAME VARCHAR(255), PRIMARY KEY (ID))
CREATE TABLE USER2MOVIE (ID INTEGER AUTO_INCREMENT NOT NULL, MOVIE INTEGER, user INTEGER, PRIMARY KEY (ID))
ALTER TABLE USER2MOVIE ADD CONSTRAINT FK_USER2MOVIE_user FOREIGN KEY (user) REFERENCES USER (ID)
